In [92]:
import numpy as np
import pandas as pd

In [93]:
from sklearn.datasets import load_iris
dataset=load_iris()

X=dataset.data
Y=dataset.target

In [22]:
df=pd.read_csv(r"C:\Users\jasme\OneDrive\Desktop\LDA_1.csv")
X=np.array(df.iloc[:,:-1])
Y=np.array(df.iloc[:,-1])

In [95]:
def between_scatter(X,Y):
    n,k=X.shape
    global_mean=X.mean(axis=0)
    Sb=np.zeros((k,k),dtype=float)
    classes,count=np.unique(Y,return_counts=True)
    for cls in classes:
        mask = (Y==cls)
        X_subset=X[mask]
        class_mean=X_subset.mean(axis=0)
        n_class=X_subset.shape[0]
        diff=(class_mean-global_mean).reshape(1,k)
        #diff = diff.reshape(k, 1)
        #Sb += n_class * (diff * diff.T)
        Sb+=n_class * diff.T * diff
    return Sb
    

In [62]:
def within_class(X,Y):
    n,k=X.shape
    classes,count=np.unique(Y,return_counts=True)
    Sw=np.zeros((k,k),dtype=float)
    for cls in classes:
        mask=(Y==cls)
        X_subset=X[mask]
        class_mean=(X_subset.mean(axis=0)).reshape(1,k)
        diff=X_subset-class_mean
        #print(diff.shape)
        Sw+=diff.T@diff
    return Sw
    

In [97]:
Sb=between_scatter(X,Y)
Sw=within_class(X,Y)
cov=np.linalg.inv(Sw)@Sb
values,vectors=np.linalg.eig(cov)

(50, 4)
(50, 4)
(50, 4)


In [98]:
cov

array([[ -3.05836939,   1.08138264,  -8.1119227 ,  -3.45864987],
       [ -5.56163926,   2.17821866, -14.96461194,  -6.30773951],
       [  8.07743878,  -2.94271854,  21.5115909 ,   9.14206468],
       [ 10.49708187,  -3.41985449,  27.54852482,  11.84588007]])

In [99]:
explained_variance=[]
for value in values:
    explained_variance.append(value*100/sum(values))

In [100]:
explained_variance

[99.12126049653669,
 0.878739503463279,
 -9.622112377133519e-15,
 1.7050877257407674e-14]

In [101]:
vectors

array([[-0.20874182, -0.00653196, -0.86693107,  0.33079214],
       [-0.38620369, -0.58661055,  0.35318765, -0.42103461],
       [ 0.55401172,  0.25256154,  0.34515744, -0.47778207],
       [ 0.7073504 , -0.76945309,  0.06749337,  0.69644146]])

In [102]:
LDA1=X.dot(vectors.T[0])

In [89]:
vectors.T[0]

array([-0.69253183, -0.72138732])

In [103]:
LDA1

array([-1.49920971, -1.2643595 , -1.35525305, -1.18495616, -1.5169559 ,
       -1.40864014, -1.28548339, -1.38431399, -1.12136823, -1.31831374,
       -1.58367182, -1.28716445, -1.31422036, -1.37605297, -1.94923317,
       -1.77516687, -1.63024483, -1.42847467, -1.50337736, -1.48893461,
       -1.35700838, -1.3795792 , -1.65506386, -1.04356034, -1.12096094,
       -1.17443134, -1.18744274, -1.46468272, -1.48146353, -1.18904953,
       -1.17130335, -1.32634064, -1.76713997, -1.85304902, -1.2475787 ,
       -1.47327677, -1.63810761, -1.56681676, -1.21538977, -1.40518817,
       -1.46300166, -0.89518633, -1.2926305 , -1.08459303, -1.19659488,
       -1.17275028, -1.50426848, -1.2789777 , -1.56279764, -1.40109479,
        0.89710107,  0.98227886,  1.138133  ,  1.09925388,  1.17128732,
        1.14140953,  1.14607006,  0.58586528,  0.97032269,  1.02272882,
        0.83027492,  0.99768699,  0.82129822,  1.20082982,  0.6250528 ,
        0.83214047,  1.22651305,  0.72534591,  1.41023091,  0.80